services:
  backend:
    build:
      target: development
    command:
      - server
      - --backend-store-uri=postgresql://postgres:${DATABASE_PASSWORD}@database:5432/${DATABASE_NAME}
      # - --registry-store-uri=<URI>
      # - --default-artifact-root=<URI>
      # - --serve-artifacts
      # - --no-serve-artifacts
      # - --artifacts-only
      - --artifacts-destination=/mlruns
      - --host=0.0.0.0
      - --port=5000
      # - --workers=<workers>
      # - --static-prefix=<static_prefix>
      # - --gunicorn-opts=<gunicorn_opts>
      # - --waitress-opts=<waitress_opts>
      # - --expose-prometheus=<expose_prometheus>
      - --app-name=basic-auth
      - --dev
    ports:
      - "5678:5678"
      - "5000:5000"

  database:
    ports:
      - "5432:5432"
