services:
  reverse-proxy:
    restart: unless-stopped
    image: traefik:v2.10
    networks:
      - backend
    command:
      - "--entrypoints.web.address=:80"
      - "--providers.docker"
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    restart: always
    build: ./backend
    depends_on:
      - database
    networks:
      - backend
    volumes:
      - ./backend/srv:/srv
      - ${MLFLOW_BASE_PATH_LOCAL}/user-data:/var/data/user-data
      - ${MLFLOW_BASE_PATH_LOCAL}/app-data:/var/data/app-data
      - ${MLFLOW_BASE_PATH_LOCAL}/mlruns-data:/mlruns
    env_file: .env
    environment:
      - MLFLOW_AUTH_CONFIG_PATH=/srv/auth_config.ini
    expose:
      - 5000
    labels:
      - "traefik.http.routers.backend.rule=Host(`${DOMAIN}`) && !PathPrefix(`/signup`)"
      - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=12884901888"
      - "traefik.http.middlewares.limit.buffering.memRequestBodyBytes=10485760"
      - "traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=12884901888"
      - "traefik.http.middlewares.limit.buffering.memResponseBodyBytes=10485760"

  frontend:
    restart: always
    build:
      context: ./frontend
      target: production
      args:
        OIDC_AUTHORITY: https://aai-demo.egi.eu/auth/realms/egi
        OIDC_CLIENT_ID: mlflow-oidc-ai4eosc
        OIDC_REDIRECT_URI: https://${DOMAIN}/signup
        PRIVACY_POLICY_URL: ${PRIVACY_POLICY_URL}
        TERMS_OF_USE_URL: ${TERMS_OF_USE_URL}
    env_file: .env
    networks:
      - backend
    depends_on:
      - backend
    labels:
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`) && PathPrefix(`/signup`)"

  database:
    image: postgres:latest
    restart: always
    #user: postgres
    # non-root user inside container!
    # (host) volume has to belong to "docker" uid:gid (e.g. lxd:docker)
    volumes:
      - ${MLFLOW_BASE_PATH_LOCAL}/app-data:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME:?DATABASE_NAME is not set}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:?DATABASE_PASSWORD is not set}
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  backup_db:
    restart: always
    build: ./backup_db
    init: true
    depends_on:
      - database
    volumes:
      - ${MLFLOW_BASE_PATH_LOCAL}/backup_db:/backup_files
      - ${MLFLOW_BASE_PATH_LOCAL}/user-data:/var/data/user-data
      - ${MLFLOW_BASE_PATH_LOCAL}/app-data:/var/data/app-data
    env_file: .env
    networks:
      - backend
    healthcheck:
      test: ["CMD", "bash"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:

#volumes:
#  user-data:
#  app-data:
#  mlruns-data:
#  backup_db:
